# Generated by Django 4.2.5 on 2023-09-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic_content',
            name='description',
            field=models.TextField(),
        ),
    ]
