# Generated by Django 4.2.5 on 2023-09-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsapp', '0002_alter_comic_content_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comic_content',
        ),
    ]
