# Generated by Django 4.2.5 on 2023-09-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsapp', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic_content',
            name='category',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
