# Generated by Django 4.2.5 on 2023-09-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsapp', '0005_comic_content_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic_content',
            name='image1',
            field=models.ImageField(null=True, upload_to='start_images'),
        ),
        migrations.AddField(
            model_name='comic_content',
            name='image2',
            field=models.ImageField(null=True, upload_to='start_images'),
        ),
        migrations.AddField(
            model_name='comic_content',
            name='image3',
            field=models.ImageField(null=True, upload_to='start_images'),
        ),
    ]
