# Generated by Django 4.2.5 on 2023-09-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsapp', '0006_comic_content_image1_comic_content_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic_content',
            name='image1',
            field=models.ImageField(null=True, upload_to='comic_images'),
        ),
        migrations.AlterField(
            model_name='comic_content',
            name='image2',
            field=models.ImageField(null=True, upload_to='comic_images'),
        ),
        migrations.AlterField(
            model_name='comic_content',
            name='image3',
            field=models.ImageField(null=True, upload_to='comic_images'),
        ),
    ]
