# Generated by Django 4.2.5 on 2023-10-04 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsapp', '0007_alter_comic_content_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic_content',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='comic_content',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='comic_content',
            name='image3',
        ),
    ]
