# Generated by Django 4.2.5 on 2023-10-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsapp', '0009_comic_content_image1_comic_content_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic_content',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
