# Generated by Django 4.2.5 on 2023-10-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsapp', '0010_comic_content_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic_content',
            name='price',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
