# Generated by Django 4.2.5 on 2023-11-02 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsapp', '0013_payment_book_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
