# Generated by Django 4.2.5 on 2024-01-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsapp', '0015_comic_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_comic_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comic_images')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('fav', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=255)),
                ('images', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('price', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
