# Generated by Django 4.2.5 on 2024-01-11 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsapp', '0016_test_comic_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test_comic_content',
        ),
    ]
