# Generated by Django 4.2.5 on 2024-01-22 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsapp', '0022_yourimagemodel_addimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
