# Generated by Django 4.2.5 on 2024-01-22 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsapp', '0023_delete_imagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddImage',
        ),
    ]
