# Generated by Django 4.2.5 on 2024-01-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsapp', '0024_delete_addimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicimages', models.ManyToManyField(blank=True, null=True, to='comicsapp.yourimagemodel')),
            ],
        ),
    ]
