# Generated by Django 4.2.5 on 2024-01-22 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsapp', '0025_addimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourimagemodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='yourimagemodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='yourimagemodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='yourimagemodel',
            name='fav',
        ),
        migrations.RemoveField(
            model_name='yourimagemodel',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='yourimagemodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='yourimagemodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='yourimagemodel',
            name='title',
        ),
    ]
