# Generated by Django 4.2.5 on 2024-01-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsapp', '0028_yourimagemodel_addimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addimage',
            name='comicimages',
        ),
        migrations.DeleteModel(
            name='comic_content',
        ),
        migrations.DeleteModel(
            name='comic_payment',
        ),
        migrations.DeleteModel(
            name='AddImage',
        ),
        migrations.DeleteModel(
            name='YourImageModel',
        ),
    ]
